#pragma config(Sensor, in3,    subPower,       sensorAnalog)
#pragma config(Sensor, dgtl1,  ledArcade,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledTank,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  hangGuide,      sensorTouch)
#pragma config(Sensor, dgtl12, clawPiston,     sensorDigitalOut)
#pragma config(Motor,  port1,           topRight,      tmotorVex393TurboSpeed_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           midRight,      tmotorVex393TurboSpeed_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port3,           bottomRight,   tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           yLiftRight,    tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port7,           yLiftLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           bottomLeft,    tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           midLeft,       tmotorVex393TurboSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port10,          topLeft,       tmotorVex393TurboSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "1064T.Carbon.Methods.c"

task main()
{



}
