#pragma config(Sensor, dgtl1,  ledTank,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledArcade,      sensorLEDtoVCC)
#pragma config(Motor,  port1,           leftFront,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightBack,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           YRightLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           YLeftLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ClawLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ClawRight,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

void pre_auton(){
}

task autonomous(){
}

task usercontrol(){
	bool useTank = true;

	if(!useTank){
		turnLEDOn(dgtl2);
		turnLEDOff(dgtl1);
	}else{
		turnLEDOn(dgtl1);
		turnLEDOff(dgtl2);
	}

	while(true){
		if(vexRT[Btn7U]){
			if(useTank){
				useTank = false;
				turnLEDOn(dgtl2);
				turnLEDOff(dgtl1);
			}else{
				useTank = true;
				turnLEDOn(dgtl1);
				turnLEDOff(dgtl2);
			}
			wait1Msec(500);
		}

		if(vexRT[Btn6U]){ // Lift up
			motor[YRightLift] = 127;
			motor[RightLift] = 127;
			motor[YLeftLift] = -127;
			motor[LeftLift] = -127;
		}
		if(vexRT[Btn5U]){// Lift down
			motor[YRightLift] = -127;
			motor[RightLift] = -127;
			motor[YLeftLift] = 127;
			motor[LeftLift] = 127;
		}
		if(vexRT[Btn6D]){ // Open claw
			motor[ClawLeft] = 127;
			motor[ClawRight] = 127;
		}
		if(vexRT[Btn5D]){ // Close claw
			motor[ClawLeft] = -127;
			motor[ClawRight] = -127;
		}

		if(useTank){
			motor[leftFront] = vexRT[Ch3];
			motor[rightFront] = -vexRT[Ch2];
			motor[leftBack] = vexRT[Ch3];
			motor[rightBack] = -vexRT[Ch2];
		}else{
			int joy_x = vexRT[Ch1];
			int joy_y = vexRT[Ch3];
			int joy_threashold = 10;

			if((abs(joy_y) > joy_threashold) && (joy_y>0)){
				motor[leftFront] = joy_y;
				motor[rightFront] = joy_y;
				motor[leftBack] = joy_y;
				motor[rightBack] = joy_y;
			}else if((abs(joy_y) > joy_threashold) && (joy_y<0)){
				motor[leftFront] = joy_y;
				motor[rightFront] = joy_y;
				motor[leftBack] = joy_y;
				motor[rightBack] = joy_y;
			}else if((abs(joy_x) > joy_threashold) && (joy_x>0)){
				motor[leftFront] = joy_x;
				motor[rightFront] = joy_x;
				motor[leftBack] = joy_x;
				motor[rightBack] = joy_x;
			}else if((abs(joy_x) > joy_threashold) && (joy_x<0)){
				motor[leftFront] = joy_x;
				motor[rightFront] = joy_x;
				motor[leftBack] = joy_x;
				motor[rightBack] = joy_x;
			}else{
				motor[leftFront] = 0;
				motor[rightFront] = 0;
				motor[leftBack] = 0;
				motor[rightBack] = 0;
			}
		}
	}
}
