#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    gyro2,          sensorGyro)
#pragma config(Sensor, in3,    subPower,       sensorAnalog)
#pragma config(Sensor, dgtl1,  ledArcade,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledTank,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  hangGuide,      sensorTouch)
#pragma config(Sensor, dgtl12, clawPiston,     sensorDigitalOut)
#pragma config(Sensor, I2C_1,  leftDrive,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightDrive,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  liftSense,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           topRight,      tmotorVex393TurboSpeed_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           midRight,      tmotorVex393TurboSpeed_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port3,           bottomRight,   tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           yLiftRight,    tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port7,           yLiftLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           bottomLeft,    tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           midLeft,       tmotorVex393TurboSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port10,          topLeft,       tmotorVex393TurboSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

//----///////////////////////////////GLOBALS/////////////////////////////////////////////////----

float wheelDiameter = 4.145;
int eDriveTicks  = 392;
int liftHeight = 0;
float liftGearDiameter = .5;
float eLiftTicks = 392;

//--------------------LCD variables-------------------------------
//Declare count variable to keep track of our choice
int driveCount = 1; //drivemodecount
int autonSelec = 0; //auton mode
//lcd buttons
const short leftButton   = 1;
const short centerButton = 2;
const short rightButton  = 4;

//----//////////////////////////////SPEAKER METHODS///////////////////////////////////////////----
void darudeSandstorm()
{
  //        140 = Tempo
  //          6 = Default octave
  //     Eighth = Default note length
  //        10% = Break between notes
  //
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   58); wait1Msec( 643);  // Note(B, Duration(Eighth .))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(32th))
  PlayTone( 1318,   58); wait1Msec( 643);  // Note(E7, Duration(Eighth .))
  PlayTone( 1318,   58); wait1Msec( 643);  // Note(E7, Duration(Eighth .))
  PlayTone( 1318,   58); wait1Msec( 643);  // Note(E7, Duration(Eighth .))
  PlayTone( 1174,   58); wait1Msec( 643);  // Note(D7, Duration(Eighth .))
  PlayTone( 1174,   58); wait1Msec( 643);  // Note(D7, Duration(Eighth .))
  PlayTone( 1320,   58); wait1Msec( 643);  // Note(A, Duration(Eighth .))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(32th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   58); wait1Msec( 643);  // Note(B, Duration(Eighth .))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(32th))
  PlayTone( 1318,   58); wait1Msec( 643);  // Note(E7, Duration(Eighth .))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   58); wait1Msec( 643);  // Note(B, Duration(Eighth .))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(32th))
  PlayTone( 1175,   58); wait1Msec( 643);  // Note(G, Duration(Eighth .))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   58); wait1Msec( 643);  // Note(B, Duration(Eighth .))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(32th))
  PlayTone( 1318,   58); wait1Msec( 643);  // Note(E7, Duration(Eighth .))
  PlayTone( 1318,   58); wait1Msec( 643);  // Note(E7, Duration(Eighth .))
  PlayTone( 1318,   58); wait1Msec( 643);  // Note(E7, Duration(Eighth .))
  PlayTone( 1174,   58); wait1Msec( 643);  // Note(D7, Duration(Eighth .))
  PlayTone( 1174,   58); wait1Msec( 643);  // Note(D7, Duration(Eighth .))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(32th))
  PlayTone( 1320,   58); wait1Msec( 643);  // Note(A, Duration(Eighth .))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   39); wait1Msec( 429);  // Note(B)
  PlayTone(    0,   19); wait1Msec( 214);  // Note(Rest, Duration(16th))
  PlayTone( 1481,   58); wait1Msec( 643);  // Note(B, Duration(Eighth .))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(32th))
  PlayTone( 1318,   58); wait1Msec( 643);  // Note(E7, Duration(Eighth .))
  return;
}

void Eyeofthe()
{
  //        112 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  587,   24); wait1Msec( 268);  // Note(D, Duration(Eighth))
  PlayTone(  659,   24); wait1Msec( 268);  // Note(E, Duration(Eighth))
  PlayTone(  698,   24); wait1Msec( 268);  // Note(F, Duration(Eighth))
  PlayTone(    0,   24); wait1Msec( 268);  // Note(Rest, Duration(Eighth))
  PlayTone(  698,   24); wait1Msec( 268);  // Note(F, Duration(Eighth))
  PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
  PlayTone(  698,   24); wait1Msec( 268);  // Note(F, Duration(Eighth))
  PlayTone(    0,   12); wait1Msec( 134);  // Note(Rest, Duration(16th))
  PlayTone(  659,   24); wait1Msec( 268);  // Note(E, Duration(Eighth))
  PlayTone(  587,   24); wait1Msec( 268);  // Note(D, Duration(Eighth))
  PlayTone(  523,   24); wait1Msec( 268);  // Note(C, Duration(Eighth))
  PlayTone(  523,   24); wait1Msec( 268);  // Note(C, Duration(Eighth))
  PlayTone(  587,   24); wait1Msec( 268);  // Note(D, Duration(Eighth))
  PlayTone(  659,   24); wait1Msec( 268);  // Note(E, Duration(Eighth))
  PlayTone(  587,   24); wait1Msec( 268);  // Note(D, Duration(Eighth))
  PlayTone(    0,   24); wait1Msec( 268);  // Note(Rest, Duration(Eighth))
  PlayTone(  587,   24); wait1Msec( 268);  // Note(D, Duration(Eighth))
  PlayTone(  659,   24); wait1Msec( 268);  // Note(E, Duration(Eighth))
  PlayTone(  698,   24); wait1Msec( 268);  // Note(F, Duration(Eighth))
  PlayTone(    0,   12); wait1Msec( 134);  // Note(Rest, Duration(16th))
  PlayTone(    0,    6); wait1Msec(  67);  // Note(Rest, Duration(32th))
  PlayTone(  659,   24); wait1Msec( 268);  // Note(E, Duration(Eighth))
  PlayTone(  698,   24); wait1Msec( 268);  // Note(F, Duration(Eighth))
  PlayTone(  783,   24); wait1Msec( 268);  // Note(G, Duration(Eighth))
  PlayTone(    0,   12); wait1Msec( 134);  // Note(Rest, Duration(16th))
  PlayTone(    0,    6); wait1Msec(  67);  // Note(Rest, Duration(32th))
  PlayTone(  698,   24); wait1Msec( 268);  // Note(F, Duration(Eighth))
  PlayTone(  783,   24); wait1Msec( 268);  // Note(G, Duration(Eighth))
  PlayTone(  880,   96); wait1Msec(1071);  // Note(A, Duration(Half))
  PlayTone(    0,   48); wait1Msec( 536);  // Note(Rest)
  PlayTone(  587,   24); wait1Msec( 268);  // Note(D, Duration(Eighth))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  587,   24); wait1Msec( 268);  // Note(D, Duration(Eighth))
  PlayTone(    0,   12); wait1Msec( 134);  // Note(Rest, Duration(16th))
  PlayTone(  523,   24); wait1Msec( 268);  // Note(C, Duration(Eighth))
  return;
}

void dangerman()
{
	//        355 = Tempo
	//          6 = Default octave
	//    Quarter = Default note length
	//        10% = Break between notes
	//
	PlayTone( 1320,   23); wait1Msec( 254);  // Note(A, Duration(Quarter .))
	PlayTone( 1175,    8); wait1Msec(  85);  // Note(G, Duration(Eighth))
	PlayTone( 1320,   15); wait1Msec( 169);  // Note(A)
	PlayTone( 1320,    8); wait1Msec(  85);  // Note(A, Duration(Eighth))
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone(  880,    8); wait1Msec(  85);  // Note(A5, Duration(Eighth))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone(  880,   15); wait1Msec( 169);  // Note(D)
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone( 1320,   23); wait1Msec( 254);  // Note(A, Duration(Quarter .))
	PlayTone( 1175,    8); wait1Msec(  85);  // Note(G, Duration(Eighth))
	PlayTone( 1320,   15); wait1Msec( 169);  // Note(A)
	PlayTone( 1320,    8); wait1Msec(  85);  // Note(A, Duration(Eighth))
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone(  880,    8); wait1Msec(  85);  // Note(A5, Duration(Eighth))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone(  880,   15); wait1Msec( 169);  // Note(D)
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone( 1320,   15); wait1Msec( 169);  // Note(A)
	PlayTone( 1320,   15); wait1Msec( 169);  // Note(A)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1046,   15); wait1Msec( 169);  // Note(C7)
	PlayTone( 1320,   30); wait1Msec( 338);  // Note(A, Duration(Half))
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone(  880,    8); wait1Msec(  85);  // Note(A5, Duration(Eighth))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone(  880,   15); wait1Msec( 169);  // Note(D)
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone( 1320,   23); wait1Msec( 254);  // Note(A, Duration(Quarter .))
	PlayTone( 1175,    8); wait1Msec(  85);  // Note(G, Duration(Eighth))
	PlayTone( 1320,   15); wait1Msec( 169);  // Note(A)
	PlayTone( 1320,    8); wait1Msec(  85);  // Note(A, Duration(Eighth))
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone(  880,    8); wait1Msec(  85);  // Note(A5, Duration(Eighth))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone(  880,   15); wait1Msec( 169);  // Note(D)
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone( 1320,   23); wait1Msec( 254);  // Note(A, Duration(Quarter .))
	PlayTone( 1175,    8); wait1Msec(  85);  // Note(G, Duration(Eighth))
	PlayTone( 1320,   15); wait1Msec( 169);  // Note(A)
	PlayTone( 1320,    8); wait1Msec(  85);  // Note(A, Duration(Eighth))
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone(  880,    8); wait1Msec(  85);  // Note(A5, Duration(Eighth))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone(  880,   15); wait1Msec( 169);  // Note(D)
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone( 1320,   15); wait1Msec( 169);  // Note(A)
	PlayTone( 1320,   15); wait1Msec( 169);  // Note(A)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1046,   15); wait1Msec( 169);  // Note(C7)
	PlayTone( 1174,   30); wait1Msec( 338);  // Note(D7, Duration(Half))
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone(  880,    8); wait1Msec(  85);  // Note(A5, Duration(Eighth))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone(  880,   15); wait1Msec( 169);  // Note(D)
	PlayTone(    0,   15); wait1Msec( 169);  // Note(Rest)
	PlayTone( 1320,   23); wait1Msec( 254);  // Note(A, Duration(Quarter .))
	PlayTone( 1320,    8); wait1Msec(  85);  // Note(A, Duration(Eighth))
	PlayTone( 1398,   46); wait1Msec( 507);  // Note(A#, Duration(Half .))
	PlayTone(  932,    8); wait1Msec(  85);  // Note(A#5, Duration(Eighth))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone(  933,   15); wait1Msec( 169);  // Note(D#)
	PlayTone(    0,   30); wait1Msec( 338);  // Note(Rest, Duration(Half))
	PlayTone( 1398,   15); wait1Msec( 169);  // Note(A#)
	PlayTone( 1398,   30); wait1Msec( 338);  // Note(A#, Duration(Half))
	PlayTone( 1109,   30); wait1Msec( 338);  // Note(F#, Duration(Half))
	PlayTone(  933,   30); wait1Msec( 338);  // Note(D#, Duration(Half))
	PlayTone( 1398,   23); wait1Msec( 254);  // Note(A#, Duration(Quarter .))
	PlayTone( 1398,    8); wait1Msec(  85);  // Note(A#, Duration(Eighth))
	PlayTone( 1481,   46); wait1Msec( 507);  // Note(B, Duration(Half .))
	PlayTone(  987,    8); wait1Msec(  85);  // Note(B5, Duration(Eighth))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone(  988,   15); wait1Msec( 169);  // Note(E)
	PlayTone(    0,   30); wait1Msec( 338);  // Note(Rest, Duration(Half))
	PlayTone( 1481,   15); wait1Msec( 169);  // Note(B)
	PlayTone( 1481,   30); wait1Msec( 338);  // Note(B, Duration(Half))
	PlayTone( 1175,   30); wait1Msec( 338);  // Note(G, Duration(Half))
	PlayTone(  988,   30); wait1Msec( 338);  // Note(E, Duration(Half))
	PlayTone( 1481,   23); wait1Msec( 254);  // Note(B, Duration(Quarter .))
	PlayTone( 1174,    8); wait1Msec(  85);  // Note(D7, Duration(Eighth))
	PlayTone( 1318,   91); wait1Msec(1014);  // Note(E7, Duration(Whole .))
	PlayTone( 1318,   15); wait1Msec( 169);  // Note(E7)
	PlayTone( 1318,    8); wait1Msec(  85);  // Note(E7, Duration(Eighth))
	PlayTone( 1318,    8); wait1Msec(  85);  // Note(E7, Duration(Eighth))
	PlayTone( 1318,   15); wait1Msec( 169);  // Note(E7)
	PlayTone( 1396,   15); wait1Msec( 169);  // Note(F7)
	PlayTone( 1396,   15); wait1Msec( 169);  // Note(F7)
	PlayTone( 1396,   15); wait1Msec( 169);  // Note(F7)
	PlayTone( 1396,   15); wait1Msec( 169);  // Note(F7)
	PlayTone( 1396,   15); wait1Msec( 169);  // Note(F7)
	PlayTone( 1396,   15); wait1Msec( 169);  // Note(F7)
	PlayTone( 1396,   15); wait1Msec( 169);  // Note(F7)
	PlayTone( 1174,   15); wait1Msec( 169);  // Note(D7)
	PlayTone( 1318,   23); wait1Msec( 254);  // Note(E7, Duration(Quarter .))
	PlayTone(    0,    8); wait1Msec(  85);  // Note(Rest, Duration(Eighth))
	PlayTone( 1481,   15); wait1Msec( 169);  // Note(B)
	PlayTone( 1318,   91); wait1Msec(1014);  // Note(E7, Duration(Whole .))
	return;
}

void ringTone(){
	//        100 = Tempo
	//          5 = Default octave
	//     Eighth = Default note length
	//        10% = Break between notes
	//
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  698,   27); wait1Msec( 300);  // Note(F, Duration(16th))
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  698,   54); wait1Msec( 600);  // Note(F)
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(    0,   54); wait1Msec( 600);  // Note(Rest)
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  698,   27); wait1Msec( 300);  // Note(F, Duration(16th))
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  698,   54); wait1Msec( 600);  // Note(F)
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(    0,   54); wait1Msec( 600);  // Note(Rest)
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  698,   27); wait1Msec( 300);  // Note(F, Duration(16th))
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  698,   54); wait1Msec( 600);  // Note(F)
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  783,   27); wait1Msec( 300);  // Note(G, Duration(16th))
	PlayTone(  783,   27); wait1Msec( 300);  // Note(G, Duration(16th))
	PlayTone(  783,   54); wait1Msec( 600);  // Note(G)
	PlayTone(  783,   54); wait1Msec( 600);  // Note(G)
	PlayTone(  880,   27); wait1Msec( 300);  // Note(A, Duration(16th))
	PlayTone(  698,   54); wait1Msec( 600);  // Note(F)
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  523,   54); wait1Msec( 600);  // Note(C)
	PlayTone(  523,   27); wait1Msec( 300);  // Note(C, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  698,   27); wait1Msec( 300);  // Note(F, Duration(16th))
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  698,   54); wait1Msec( 600);  // Note(F)
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(    0,   54); wait1Msec( 600);  // Note(Rest)
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  698,   27); wait1Msec( 300);  // Note(F, Duration(16th))
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  698,   54); wait1Msec( 600);  // Note(F)
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(    0,   54); wait1Msec( 600);  // Note(Rest)
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  698,   27); wait1Msec( 300);  // Note(F, Duration(16th))
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  698,   54); wait1Msec( 600);  // Note(F)
	PlayTone(  659,   54); wait1Msec( 600);  // Note(E)
	PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  587,   27); wait1Msec( 300);  // Note(D, Duration(16th))
	PlayTone(  783,   27); wait1Msec( 300);  // Note(G, Duration(16th))
	PlayTone(  783,   27); wait1Msec( 300);  // Note(G, Duration(16th))
	PlayTone(  783,   54); wait1Msec( 600);  // Note(G)
	PlayTone(  783,   54); wait1Msec( 600);  // Note(G)
	PlayTone(  880,   27); wait1Msec( 300);  // Note(A, Duration(16th))
	PlayTone(  698,   54); wait1Msec( 600);  // Note(F)
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	PlayTone(  523,   54); wait1Msec( 600);  // Note(C)
	PlayTone(  523,   27); wait1Msec( 300);  // Note(C, Duration(16th))
	PlayTone(  587,   54); wait1Msec( 600);  // Note(D)
	return;
}

//----///////////////////////////////DRIVER METHODS///////////////////////////////////////////----

void time(int Msecs){//This method pauses code for a specified time
	wait1Msec(Msecs);
}

void lift(int power){//User csontrol method controls the robots lift (positive power raises the lift
	motor[yLiftRight] =  power;
	motor[yLiftLeft]  = -power;
}

void liftTime(int power, int ms){
	motor[yLiftRight] =  power;
	motor[yLiftLeft]  = -power;
	time(ms);
}

void stopLift(int ms){
	motor[yLiftRight] =  0;
	motor[yLiftLeft]  =  0;
	time(ms);
}

void stopLiftW(){
	motor[yLiftRight] =  0;
	motor[yLiftLeft]  =  0;
}

void autonClaw(int open){
	if (open == 1){
		SensorValue[clawPiston] = 1;
	}
	else{
		SensorValue[clawPiston] = 0;
	}
}

void autonLift(int speed, int height){////////////////The distance of rotation wanted should be * by the gear ratio/////
	nMotorEncoder[liftSense]  = 0;
	int ticks = height/(liftGearDiameter*PI) * eLiftTicks;
	while (abs(nMotorEncoder[liftSense])<ticks*.6){

		lift(speed);
	}
	while(abs(nMotorEncoder[leftDrive]) < ticks){

		lift(speed);
	}
	liftTime(-speed*.3,50);
	stopLift(50);
}

void drive(int left, int right){//Tank drive control method
	motor[topLeft]     =  left;
	motor[midLeft]     = -left;
	motor[bottomLeft]  =  left;
	motor[topRight]    =  right;
	motor[midRight]    = -right;
	motor[bottomRight] =  right;
}

void driveTime(int left, int right, int ms){//Tank drive auton control method
	motor[topLeft]     =  left;
	motor[midLeft]     = -left;
	motor[bottomLeft]  =  left;
	motor[topRight]    =  right;
	motor[midRight]    = -right;
	motor[bottomRight] =  right;
	time(ms);
}

void stopDrive(int timeLength){ //stop the drive
	motor[topLeft]     =  0;
	motor[midLeft]     =  0;
	motor[bottomLeft]  =  0;
	motor[topRight]    =  0;
	motor[midRight]    =  0;
	motor[bottomRight] =  0;
	time(timeLength);
}

void autoDrive(int speed, int dist){///////////////////in development///////////////////////
	nMotorEncoder[leftDrive]  = 0;
	int ticks = dist/(wheelDiameter*PI) * eDriveTicks;
	while (abs(nMotorEncoder[leftDrive])<ticks*.6){

		motor[topLeft]     =  speed;
		motor[midLeft]     = -speed;
		motor[bottomLeft]  =  speed;
		motor[topRight]    = -speed;
		motor[midRight]    =  speed;
		motor[bottomRight] = -speed;
	}
	while(abs(nMotorEncoder[leftDrive]) < ticks){

		motor[topLeft]     =  speed/3;
		motor[midLeft]     = -speed/3;
		motor[bottomLeft]  =  speed/3;
		motor[topRight]    = -speed/3;
		motor[midRight]    =  speed/3;
		motor[bottomRight] = -speed/3;
	}
	driveTime(-speed*.3,speed*.3,50);
	stopDrive(50);
}

//----///////////////////////////////SENSOR METHODS//////////////////////////////////////////----

void resetGyro(){ //resets the Gryos during the robots start up
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
	SensorType[in1] = sensorNone;
	SensorType[in2] = sensorNone;
	wait1Msec(500);

	//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[in1] = sensorGyro;
	SensorType[in2] = sensorGyro;
	wait1Msec(1500);

}

void gyroValue(){
	displayLCDCenteredString(0,"Gyro Value");
	displayLCDNumber(1,5,(SensorValue[in1]+SensorValue[in2])/2,5);
}

void gyroTurn(int degrees2){

	//Specify the number of degrees for the robot to turn (1 degree = 10, or 900 = 90 degrees)
	int degrees10 = degrees2;
	//Specify the amount of acceptable error in the turn
	int error = 50;

	//While the absolute value of the gyro is less than the desired rotation - 100...
	while((SensorValue[in1] + SensorValue[in2])/2 < degrees10*.5)
	{
		motor[topLeft]     = -80;
		motor[midLeft]     =  80;
		motor[bottomLeft]  = -80;
		motor[topRight]    = -80;
		motor[midRight]    =  80;
		motor[bottomRight] = -80;
	}
	//Brief brake to eliminate some drift
	motor[topLeft]     =  10;
	motor[midLeft]     = -10;
	motor[bottomLeft]  =  10;
	motor[topRight]    =  10;
	motor[midRight]    = -10;
	motor[bottomRight] =  10;
	wait1Msec(100);

	//Second while loop to move the robot more slowly to its goal, also setting up a range
	//for the amount of acceptable error in the system
	while((SensorValue[in1] + SensorValue[in2])/2 > degrees10 + error || (SensorValue[in1] + SensorValue[in2])/2 < degrees10 - error)
	{
		if((SensorValue[in1] + SensorValue[in2])/2 > degrees10)
		{
			motor[topLeft]     =  50;
			motor[midLeft]     = -50;
			motor[bottomLeft]  =  50;
			motor[topRight]    =  50;
			motor[midRight]    = -50;
			motor[bottomRight] =  60;
		}
		else
		{
			motor[topLeft]     = -50;
			motor[midLeft]     =  50;
			motor[bottomLeft]  = -50;
			motor[topRight]    = -50;
			motor[midRight]    =  50;
			motor[bottomRight] = -50;
		}
	}
	//Stop
	motor[topLeft]     =  0;
	motor[midLeft]     =  0;
	motor[bottomLeft]  =  0;
	motor[topRight]    =  0;
	motor[midRight]    =  0;
	motor[bottomRight] =  0;
	wait1Msec(100);
}

//----///////////////////////////////Auton Selections////////////////////////////////////////----
void auton2(){ //////////////////////Skills////////////////////////////////////////
	autoDrive(127,12);
}

//----//////////////////////////Blue Auton Selections////////////////////////////////////////----
void auton5(){
	time(1);
}
void auton6(){
	time(1);
}
void auton7(){
	time(1);
}
void auton8(){
	time(1);
}
void auton9(){
	time(1);
}

//----///////////////////////////Red Auton Selections////////////////////////////////////////----

void auton20(){
	time(1);
}
void auton21(){
	time(1);
}
void auton22(){
	time(1);
}
void auton23(){
	time(1);
}
void auton24(){
	time(1);
}

void displayBatteryValues(){ //displays power levels
	string mainBatteryVoltage, expanderBattery;
	displayLCDString(0,0,"Cor Power: ");
	displayLCDString(1,0,"Sub Power: ");
	sprintf(mainBatteryVoltage,"%1.2f%c",nImmediateBatteryLevel/1000.0,'V');
	sprintf(expanderBattery,"%1.2f%c",SensorValue[subPower]/283.2, 'V');
	displayLCDString(0,10,mainBatteryVoltage);
	displayLCDString(1,10,expanderBattery);
}

void resetLcd(){
	bLCDBacklight = true;
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
}

void waitForPress(){//Pauses the lcd display until a button is pressed
	while(nLCDButtons == 0){}
	time(5);
}

void waitForRelease(){//Pauses the lcd display until a button is released
	while(nLCDButtons != 0){}
	time(5);
}

void selectAuton(){
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton){
		switch(autonSelec){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Playing Lft Side?");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec = 2;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			else{
				waitForRelease();
				autonSelec=5;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Playing Rt Side?");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			else{
				waitForRelease();
				autonSelec = 20;
			}
			break;
		case 2:
			//Skills
			displayLCDCenteredString(0, "Skills");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec=0;
			}
			break;
		case 5://<///////////////////////////////////////Blue Lcd Autons////////////////////////////////////////////////////////>
			displayLCDCenteredString(0, "1B) R fence/hang");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec=50;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			break;
		case 6:
			displayLCDCenteredString(0, "1B) L fence/hang");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			break;
		case 7:
			displayLCDCenteredString(0, "2B) R  Clear All");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			break;
		case 8:
			displayLCDCenteredString(0, "2B) L  Clear All");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			break;
		case 9:
			displayLCDCenteredString(0, "auto Dist");
			displayLCDCenteredString(1, "enter");
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				autonSelec = 50;
			}
			break;
		case 50:
			displayLCDCenteredString(0,"Go Back");
			displayLCDCenteredString(1,"<    Enter     >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec=9;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec=5;
			}
			else if(nLCDButtons == centerButton){
				waitForRelease();
				autonSelec=0;
			}
			break;
			//<//////////////////////////////////////////////////////////////RED Autons///////////////////////////////////////////>
		case 20:
			displayLCDCenteredString(0, "1B) R fence/hang");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec=51;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			break;
		case 21:
			displayLCDCenteredString(0, "1B) L fence/hang");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			break;
		case 22:
			displayLCDCenteredString(0, "2B) R  Clear All");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			break;
		case 23:
			displayLCDCenteredString(0, "slot");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec++;
			}
			break;
		case 24:
			displayLCDCenteredString(0, "slot");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec=51;
			}
			break;
		case 51:
			displayLCDCenteredString(0,"Go Back");
			displayLCDCenteredString(1,"<    Enter     >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				autonSelec=24;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				autonSelec=20;
			}
			else if(nLCDButtons == centerButton){
				waitForRelease();
				autonSelec=0;
			}
			break;
		default:
			autonSelec = 0;
			break;
		}
		time(10);
	}
}

void nothing(){ //Display emtpy slot on the lcd
	displayLCDCenteredString(0, "slot");
	displayLCDCenteredString(1, "here");
	time(10);
}
void lcdAuton(){ //autonomous selection on lcd
	resetLcd();
	//Switch Case that actually runs the user choice
	switch(autonSelec){
	case 2:
		auton2();
		break;
	case 5:
		auton5();
		break;
	case 6:
		auton6();
		break;
	case 7:
		auton7();
		break;
	case 8:
		auton8();
		break;
	case 9:
		auton9();
		break;
	case 20:
		auton20();
		break;
	case 21:
		auton21();
		break;
	case 22:
		auton22();
		break;
	case 23:
		auton23();
		break;
	case 24:
		auton24();
		break;
	}
}
