#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	bool isMotorOn = true;
	while(true){
		if(vexRT[Btn5U]){
			if(isMotorOn){
				isMotorOn = false;
			}else{
				isMotorOn = true;
			}
		}

		if(isMotorOn){
			motor[frontLeft] = 127;
			motor[frontRight] = -127;
			motor[backLeft] = 127;
			motor[backRight] = -127;
		}else{
			motor[frontLeft] = 0;
			motor[frontRight] = 0;
			motor[backLeft] = 0;
			motor[backRight] = 0;
		}
	}
}
